### ISSUE TITLE
Failed to get replSet status. oplog_status.go, Failed to get local.oplog_rs collection stats.

### ISSUE THREAD

**Issue by ghost** [dcu/mongodb_exporter#100]
Hello, 

I have a local running instance of mongodb with prometheus 
```
#prom yml
scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:9001']
```

However when I run the mongodb_exporter, I am getting this:

$ ./mongodb_exporter-darwin-amd64
Listening on :9001 (scheme=HTTP, secured=no, clientValidation=no)
E0604 13:01:13.175465    2063 replset_status.go:232] Failed to get replSet status.
E0604 13:01:13.176202    2063 oplog_status.go:127] Failed to get local.oplog_rs collection stats.

Data is being inserted 

```
> db.people.find({"name": "Ale"}).count()
236520
> db.people.find({"name": "Ale"}).count()
240247
```

Many Thanks

Aidy
